name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get remove clang-* llvm-*
          sudo apt-get update && sudo apt-get install -y clang-14 llvm-14 libclang-14-dev cmake git

      - name: Set up Clang and cmake
        run: |
          export CC=/usr/bin/clang-14
          export CXX=/usr/bin/clang++-14
          export LDFLAGS="-L/usr/lib/llvm-14/lib"
          export CXXFLAGS="-I/usr/lib/llvm-14/include -frtti"

      - name: Run build script
        run: tools/build.sh

  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cmake-format

      - name: Run format script
        run: tools/format.sh

      - name: Check for uncommitted changes after formatting
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Code format issues detected. Run tools/format.sh and commit the changes."
            git diff
            exit 1
          fi